# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Runs all the tests'
  lane :test do
    gradle(task: 'test')
  end

  desc 'Generate screenshots'
  lane :screenshots do
    gradle(
      task: 'clean assembleDebug assembleAndroidTest'
    )
    capture_android_screenshots
  end

  desc 'Submit a new Beta Build to Crashlytics Beta and Play Beta'
  lane :beta do
    # First of all generate screenshots
    # TODO: Fix screenshots on travis
    # screenshots

    # Build app
    gradle(
      task: 'clean assemble',
      build_type: 'Release',
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => 'tmp-keystore.jks',
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEYSTORE_KEY_PASSWORD']
      }
    )

    # Generate changelogs
    changelog_from_git_commits

    # Upload to crashlytics
    crashlytics(
      api_token: ENV['FABRIC_API_TOKEN'],
      build_secret: ENV['FABRIC_BUILD_SECRET']
    )

    # Supply to beta track
    supply(track: 'beta')

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc 'Deploy a new version to the Google Play'
  lane :deploy do
    gradle(
      task: 'clean assemble',
      build_type: 'Release'
    )
    upload_to_play_store
  end
end
